In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Preprocess the data

data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [4]:
# Encode Categorical variables

label_encoder_gender = LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [5]:
# One-hot encode for Geography

onehot_encoder_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoded=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [6]:
## Combine one hot encoded columns with original data

data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [7]:
# Split the data into features and target

X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [8]:
# Split the data into training and testing
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
## Scale
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [10]:
# Save the encoders and scaler for later use

with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

# ANN Regression Problem Statement

In [11]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING:tensorflow:From c:\Users\nelso\Desktop\College\3Ano\2Semestre\Estagio\Udemy2\13-ANN_Classification\myenv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [12]:
model=Sequential(
    [
        Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
        Dense(32,activation='relu'),
        Dense(1) # Output layer for regression
    ]
)

## Compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

WARNING:tensorflow:From c:\Users\nelso\Desktop\College\3Ano\2Semestre\Estagio\Udemy2\13-ANN_Classification\myenv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From c:\Users\nelso\Desktop\College\3Ano\2Semestre\Estagio\Udemy2\13-ANN_Classification\myenv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [13]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

#Set up TensorBoard

log_dir="regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [14]:
# Set up Early Stopping

early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [15]:
# Train the model

history=model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    callbacks=[early_stopping_callback,tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\nelso\Desktop\College\3Ano\2Semestre\Estagio\Udemy2\13-ANN_Classification\myenv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\nelso\Desktop\College\3Ano\2Semestre\Estagio\Udemy2\13-ANN_Classification\myenv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 1s 2ms/step - loss: 100358.3828 - mae: 100358.3828 - val_loss: 98440.6406 - val_mae: 98440.6406
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 99330.4375 - mae: 99330.4375 - val_loss: 96353.1016 - val_mae: 96353.1016
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 95729.4297 - mae: 95729.4297 - val_loss: 91101.5547 - val_mae: 91101.5547
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 88833.1719 - mae: 88833.1719 - val_loss: 82773.3281 - val_mae: 82773.3281
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 79357.4297 - mae: 79357.4297 - val_loss: 72905.6250 - val_mae: 72905.6250
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 69205.1016 - mae: 69205.1016 - val_loss: 63746.8242 - val_mae: 63746.8242
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 60609.6523 - mae: 60609.6523 - val_loss: 56943.9727 - val_mae: 56943.9727
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 55066.9844 - mae: 55066.9844 - val_loss: 53369.1641 - val_mae: 53369.1641
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 52264.5859 - mae: 52264.5859 - val_loss: 51903.1328 - val_mae: 51903.1328
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 51099.6602 - mae: 51099.6602 - val_loss: 51393.4023 - val_mae: 51393.4023
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 50644.4648 - mae: 50644.4648 - val_loss: 51172.6680 - val_mae: 51172.6680
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 50440.3203 - mae: 50440.3203 - val_loss: 51042.6758 - val_mae: 51042.6758
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 50316.6445 - mae: 50316.6445 - val_loss: 50943.7852 - val_mae: 50943.7852
Epoch 14/100
250/250 [==============================] - 0s 2ms/step - loss: 50221.1016 - mae: 50221.1016 - val_loss: 50881.2188 - val_mae: 50881.2188
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 50150.7695 - mae: 50150.7695 - val_loss: 50823.6445 - val_mae: 50823.6445
Epoch 16/100
250/250 [==============================] - 0s 2ms/step - loss: 50083.5195 - mae: 50083.5195 - val_loss: 50756.3984 - val_mae: 50756.3984
Epoch 17/100
250/250 [==============================] - 0s 2ms/step - loss: 50029.5469 - mae: 50029.5469 - val_loss: 50711.1289 - val_mae: 50711.1289
Epoch 18/100
250/250 [==============================] - 0s 2ms/step - loss: 49983.1406 - mae: 49983.1406 - val_loss: 50682.9414 - val_mae: 50682.9414
Epoch 19/100
250/250 [==============================] - 0s 2ms/step - loss: 49935.1641 - mae: 49935.1641 - val_loss: 50620.4570 - val_mae: 50620.4570
Epoch 20/100
250/250 [==============================] - 0s 2ms/step - loss: 49898.3789 - mae: 49898.3789 - val_loss: 50583.7539 - val_mae: 50583.7539
Epoch 21/100
250/250 [==============================] - 0s 2ms/step - loss: 49863.6172 - mae: 49863.6172 - val_loss: 50552.8086 - val_mae: 50552.8086
Epoch 22/100
250/250 [==============================] - 1s 2ms/step - loss: 49832.7266 - mae: 49832.7266 - val_loss: 50526.7578 - val_mae: 50526.7578
Epoch 23/100
250/250 [==============================] - 0s 2ms/step - loss: 49803.3398 - mae: 49803.3398 - val_loss: 50503.7578 - val_mae: 50503.7578
Epoch 24/100
250/250 [==============================] - 0s 2ms/step - loss: 49780.0898 - mae: 49780.0898 - val_loss: 50479.9062 - val_mae: 50479.9062
Epoch 25/100
250/250 [==============================] - 0s 2ms/step - loss: 49751.8164 - mae: 49751.8164 - val_loss: 50461.8750 - val_mae: 50461.8750
Epoch 26/100
250/250 [==============================] - 1s 2ms/step - loss: 49733.8164 - mae: 49733.8164 - val_loss: 50446.3789 - val_mae: 50446.3789
Epoch 27/100
250/250 [==============================] - 0s 2ms/step - loss: 49712.4453 - mae: 49712.4453 - val_loss: 50419.2969 - val_mae: 50419.2969
Epoch 28/100
250/250 [==============================] - 0s 2ms/step - loss: 49691.2969 - mae: 49691.2969 - val_loss: 50414.5508 - val_mae: 50414.5508
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 49675.2734 - mae: 49675.2734 - val_loss: 50393.4219 - val_mae: 50393.4219
Epoch 30/100
250/250 [==============================] - 0s 2ms/step - loss: 49651.9805 - mae: 49651.9805 - val_loss: 50381.5898 - val_mae: 50381.5898
Epoch 31/100
250/250 [==============================] - 0s 2ms/step - loss: 49635.1055 - mae: 49635.1055 - val_loss: 50383.2383 - val_mae: 50383.2383
Epoch 32/100
250/250 [==============================] - 0s 2ms/step - loss: 49621.4688 - mae: 49621.4688 - val_loss: 50375.4570 - val_mae: 50375.4570
Epoch 33/100
250/250 [==============================] - 0s 2ms/step - loss: 49609.0156 - mae: 49609.0156 - val_loss: 50358.9766 - val_mae: 50358.9766
Epoch 34/100
250/250 [==============================] - 0s 2ms/step - loss: 49593.7070 - mae: 49593.7070 - val_loss: 50348.6797 - val_mae: 50348.6797
Epoch 35/100
250/250 [==============================] - 0s 2ms/step - loss: 49580.2812 - mae: 49580.2812 - val_loss: 50344.4609 - val_mae: 50344.4609
Epoch 36/100
250/250 [==============================] - 0s 2ms/step - loss: 49568.0469 - mae: 49568.0469 - val_loss: 50340.7266 - val_mae: 50340.7266
Epoch 37/100
250/250 [==============================] - 0s 2ms/step - loss: 49556.2383 - mae: 49556.2383 - val_loss: 50332.3867 - val_mae: 50332.3867
Epoch 38/100
250/250 [==============================] - 0s 2ms/step - loss: 49544.6133 - mae: 49544.6133 - val_loss: 50318.2617 - val_mae: 50318.2617
Epoch 39/100
250/250 [==============================] - 0s 2ms/step - loss: 49539.3906 - mae: 49539.3906 - val_loss: 50309.2188 - val_mae: 50309.2188
Epoch 40/100
250/250 [==============================] - 1s 2ms/step - loss: 49527.0586 - mae: 49527.0586 - val_loss: 50311.7383 - val_mae: 50311.7383
Epoch 41/100
250/250 [==============================] - 1s 2ms/step - loss: 49521.8359 - mae: 49521.8359 - val_loss: 50303.8047 - val_mae: 50303.8047
Epoch 42/100
250/250 [==============================] - 1s 2ms/step - loss: 49510.2383 - mae: 49510.2383 - val_loss: 50300.0664 - val_mae: 50300.0664
Epoch 43/100
250/250 [==============================] - 1s 2ms/step - loss: 49503.1484 - mae: 49503.1484 - val_loss: 50295.2461 - val_mae: 50295.2461
Epoch 44/100
250/250 [==============================] - 0s 2ms/step - loss: 49494.1562 - mae: 49494.1562 - val_loss: 50282.1328 - val_mae: 50282.1328
Epoch 45/100
250/250 [==============================] - 0s 2ms/step - loss: 49485.3984 - mae: 49485.3984 - val_loss: 50279.5430 - val_mae: 50279.5430
Epoch 46/100
250/250 [==============================] - 1s 2ms/step - loss: 49479.7930 - mae: 49479.7930 - val_loss: 50282.5859 - val_mae: 50282.5859
Epoch 47/100
250/250 [==============================] - 0s 2ms/step - loss: 49472.8984 - mae: 49472.8984 - val_loss: 50283.6797 - val_mae: 50283.6797
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 49463.7422 - mae: 49463.7422 - val_loss: 50293.7344 - val_mae: 50293.7344
Epoch 49/100
250/250 [==============================] - 0s 2ms/step - loss: 49455.9258 - mae: 49455.9258 - val_loss: 50273.3867 - val_mae: 50273.3867
Epoch 50/100
250/250 [==============================] - 0s 2ms/step - loss: 49447.7734 - mae: 49447.7734 - val_loss: 50274.8125 - val_mae: 50274.8125
Epoch 51/100
250/250 [==============================] - 0s 2ms/step - loss: 49443.7188 - mae: 49443.7188 - val_loss: 50283.5898 - val_mae: 50283.5898
Epoch 52/100
250/250 [==============================] - 0s 2ms/step - loss: 49436.1445 - mae: 49436.1445 - val_loss: 50278.3672 - val_mae: 50278.3672
Epoch 53/100
250/250 [==============================] - 0s 2ms/step - loss: 49430.4062 - mae: 49430.4062 - val_loss: 50264.0469 - val_mae: 50264.0469
Epoch 54/100
250/250 [==============================] - 0s 2ms/step - loss: 49427.1797 - mae: 49427.1797 - val_loss: 50272.2383 - val_mae: 50272.2383
Epoch 55/100
250/250 [==============================] - 0s 2ms/step - loss: 49419.7695 - mae: 49419.7695 - val_loss: 50293.1836 - val_mae: 50293.1836
Epoch 56/100
250/250 [==============================] - 0s 2ms/step - loss: 49418.0703 - mae: 49418.0703 - val_loss: 50280.6367 - val_mae: 50280.6367
Epoch 57/100
250/250 [==============================] - 0s 2ms/step - loss: 49409.9766 - mae: 49409.9766 - val_loss: 50266.6562 - val_mae: 50266.6562
Epoch 58/100
250/250 [==============================] - 0s 2ms/step - loss: 49406.1875 - mae: 49406.1875 - val_loss: 50280.2422 - val_mae: 50280.2422
Epoch 59/100
250/250 [==============================] - 0s 2ms/step - loss: 49402.3008 - mae: 49402.3008 - val_loss: 50279.3750 - val_mae: 50279.3750
Epoch 60/100
250/250 [==============================] - 0s 2ms/step - loss: 49394.8984 - mae: 49394.8984 - val_loss: 50279.7148 - val_mae: 50279.7148
Epoch 61/100
250/250 [==============================] - 0s 2ms/step - loss: 49390.0664 - mae: 49390.0664 - val_loss: 50273.1172 - val_mae: 50273.1172
Epoch 62/100
250/250 [==============================] - 0s 2ms/step - loss: 49386.9062 - mae: 49386.9062 - val_loss: 50287.3984 - val_mae: 50287.3984
Epoch 63/100
250/250 [==============================] - 0s 2ms/step - loss: 49380.4961 - mae: 49380.4961 - val_loss: 50285.6914 - val_mae: 50285.6914

In [16]:
%load_ext tensorboard

In [24]:
%tensorboard --logdir regressionlogs/fit

ERROR: Failed to launch TensorBoard (exited with 1).

In [25]:
## Evaluate model on the test data

test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE: {test_mae}')

63/63 [==============================] - 0s 2ms/step - loss: 50264.0469 - mae: 50264.0469
Test MAE: 50264.046875

In [26]:
model.save('regression_model.h5')

c:\Users\nelso\Desktop\College\3Ano\2Semestre\Estagio\Udemy2\13-ANN_Classification\myenv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(